title: x401
description: An open standard for internet-native agent authorization
url: ""
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
